---
title: "Test Graphs - Interactive"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}

# load required packages
library(flexdashboard)
library(data.table)
library(tidyverse)
library(broom)
library(lubridate)
library(plotly)
library(shiny)

# load saved data
df_absent <- readRDS("df_absent.rds")
```

Column {.sidebar}
----------------------------------------------------------------------

Toggle the drop down menu below to select a demographic category to view. 
\
\
ELL = English Language Learner 
\
SWD = Student with Disability 
\
STH = Student in Temporary Housing

```{global r}

# a few modification to the data frame 
df_absent <- df_absent %>% 
  mutate(Year = ymd(paste0(substr(Year, 1, 4), "-01-01")), # change to data format, taking first year
         chronic_absent_pct = round(chronic_absent_pct,2)) # round chronic absenteeism rate

# Set the input that the graph in the next chunk will loop through
selectInput(inputId = "varname", 
            label = "Demographic Category:", 
            choices = unique(df_absent$Demographic.Category), 
            selected = "All Students", # this is the default
            multiple = F) # change to TRUE for option for multiple inputs at once 


```

Column 
-----------------------------------------------------------------------

### Chronic Absenteeism Over Time by Demographic Category

```{r}

# big graph: line by ethnicity, scroll over for details
renderPlot({
  df_absent %>% 
  filter(Demographic.Category == input$varname) %>% # change to %in% if allowing multiple inputs at once
  ggplot() +
  # inheret.aes = FALSE for geom_line, otherwise does not show up with custom text
  geom_line(aes(x =Year, y=chronic_absent_pct, color =Demographic.Variable), inherit.aes = F) +
  geom_point(aes(x =Year, y=chronic_absent_pct, color=Demographic.Variable)) + 
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  scale_y_continuous(
    limits = c(0, 60),       # Start y-axis at 0
    expand = c(0, 0)         # Prevent padding
  ) +
  labs(
    title = "",
    x = "Year",
    y = "Chronic Absenteeism (%)",
    color = ""
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 45, hjust = 1), # Rotate x-axis labels for readability
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 9))
})



# ggplotly(, tooltip = "text") # adapts "text" aesthetic from above
```




